apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sts-webhook
webhooks:
  - name: sts-webhook.{{namespace}}.svc
    clientConfig:
      caBundle: {{caBundle}}
      url: https://{{local_ip}}:9443/mutate-apps-v1-statefulset
    matchPolicy: Exact
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        resources:
          - statefulsets
        operations:
          - CREATE
          - UPDATE
        scope:
          '*' # 匹配范围，"*" 匹配所有资源，但不包括子资源，"*/*" 匹配所有资源，包括子资源
    namespaceSelector: { }
    failurePolicy: Fail
    sideEffects: None
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values:
            - sts-webhook
    admissionReviewVersions:
      - v1
